<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage2.master" CodeFile="BillInfo.aspx.cs" Inherits="Checkout" %>



<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
   
    
        
        You Bill:
    
        <br />
        <br/>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" Width="255px" CellPadding="6" CellSpacing="4" ForeColor="#333333" GridLines="None" Font-Size="Small" OnRowDeleting="GridView1_RowDeleting">
            <AlternatingRowStyle BackColor="White" />
            <EditRowStyle BackColor="#7C6F57" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F8FAFA" />
            <SortedAscendingHeaderStyle BackColor="#246B61" />
            <SortedDescendingCellStyle BackColor="#D4DFE1" />
            <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>
        
   
        
            <table style="width: 511px; position: static; height: 100px; color: #000000; font-size: medium;">
            <tr>
                <td colspan="3">
                    <asp:Label ID="Label1" runat="server" Font-Bold="True" Style="position: static" Text="Select Payment Method>>>"
                        Width="193px"></asp:Label></td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Label ID="Label2" runat="server" Font-Bold="True" Style="position: static" Text="Payment by Credit Card>>"
                        Width="188px"></asp:Label></td>
                <td style="width: 100px">
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:RadioButton ID="RadioButton1" runat="server" Style="position: static" GroupName="a" Text="Master Card" Width="115px" /></td>
                <td style="width: 100px">
                    <asp:Image ID="Image1" runat="server" Height="30px" ImageUrl="~/Creditcards/mastercard.jpg"
                        Style="position: static" Width="150px" /></td>
                <td style="width: 100px">
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:RadioButton ID="RadioButton2" runat="server" Style="position: static" GroupName="a" Text="Visa" Width="115px" /></td>
                <td style="width: 100px">
                    <asp:Image ID="Image2" runat="server" Height="30px" ImageUrl="~/Creditcards/visa.jpg"
                        Style="position: static" Width="150px" />&nbsp;</td>
                <td style="width: 100px">
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Label ID="Label3" runat="server" Font-Bold="True" Style="position: static" Text="Payment by Debit Card>>"
                        Width="188px"></asp:Label></td>
                <td style="width: 100px">
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:RadioButton ID="RadioButton3" runat="server" Style="position: static" GroupName="a" Text="Axis Bank" Width="115px" /></td>
                <td style="width: 100px">
                    <asp:Image ID="Image3" runat="server" Height="30px" ImageUrl="~/debitcards/axisbank.gif"
                        Style="position: static" Width="150px" /></td>
                <td style="width: 100px">
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:RadioButton ID="RadioButton4" runat="server" Style="position: static" GroupName="a" Text="HDFC Bank" /></td>
                <td style="width: 100px">
                    <asp:Image ID="Image4" runat="server" Height="30px" ImageUrl="~/debitcards/hdfcbank.gif"
                        Style="position: static" Width="150px" /></td>
                <td style="width: 100px">
                </td>
            </tr>
            <tr>
                <td class="auto-style2">
                    <asp:RadioButton ID="RadioButton5" runat="server" Style="position: static" GroupName="a" Text="Citi Bank" Width="116px" /></td>
                <td style="width: 100px; height: 22px">
                    <asp:Image ID="Image5" runat="server" Height="30px" ImageUrl="~/debitcards/citibakk.gif"
                        Style="position: static" Width="150px" /></td>
                <td style="width: 100px; height: 22px">
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    Other&gt;&gt;&nbsp;</td>
                <td style="width: 100px">
                </td>
                <td style="width: 100px">
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:RadioButton ID="RadioButton6" runat="server" GroupName="a" Text="Cash On Delivery" />
                </td>
                <td style="width: 100px">
                    &nbsp;</td>
                <td style="width: 100px">
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    &nbsp;</td>
                <td style="width: 100px">
                    <asp:Button ID="btncontinue" runat="server" Style="position: static" Text="Continue" OnClick="btncontinue_Click" Width="72px" /></td>
                <td style="width: 100px">
                    &nbsp;</td>
            </tr>
        </table>
  </asp:Content>